import React from 'react'

function PrivacyPolicy() {
  return (
    <div>
        <h1 style={{padding:'20px'}}>PRIVACY POLICY</h1>
        <p style={{padding:'20px'}}>OUR PRIVACY POLICY, HEREIN REFERRED TO AS THE “PRIVACY POLICY,” HAS BEEN METICULOUSLY CRAFTED TO PROVIDE YOU, OUR ESTEEMED USER (“USER”), WITH COMPREHENSIVE INSIGHTS INTO HOW WE GATHER, SAFEGUARD, AND UTILIZE BOTH YOUR PERSONAL AND NON-PERSONAL INFORMATION. THESE CLASSIFICATIONS ARE DETERMINED BY THEIR MANDATORY OR VOLUNTARY NATURE, CHOSEN BY YOU WHEN ACCESSING THE YOURINDIANSHOP WEBSITE AND ITS AFFILIATED NETWORKS. OUR PRIMARY GOAL IS TO EMPOWER YOU TO MAKE WELL-INFORMED DECISIONS ABOUT SHARING INFORMATION, UNDERSCORING THE CHOICES AT YOUR DISPOSAL REGARDING THE DISCLOSURE OF SUCH INFORMATION TO US. PERSONAL INFORMATION, AS DEFINED HEREIN, ENCOMPASSES DATA THAT, EITHER ON ITS OWN OR WHEN COUPLED WITH ADDITIONAL INFORMATION, CAN READILY IDENTIFY, CONTACT, OR LOCATE YOU.
        BY UTILIZING THE YOURINDIANSHOP PLATFORM, OR ANY THIRD-PARTY PLATFORMS LINKED TO IT, YOU EXPRESSLY AGREE TO ADHERE TO ITS INTENDED USE. SHOULD YOU DISSENT FROM THE TERMS OUTLINED IN THIS POLICY, WE RECOMMEND DISCONTINUING THE USE OF OUR SERVICES.
        YOUR ACCESS, TRANSACTIONS, OR ANY FORM OF ENGAGEMENT WITH THE PLATFORM SIGNIFY YOUR UNEQUIVOCAL ACCEPTANCE OF ALL TERMS OF USE AND SUBSCRIPTIONS ASSOCIATED WITH YOURINDIANSHOP. FOR FURTHER CLARIFICATION ON PLATFORM USAGE, WE ENCOURAGE YOU TO CAREFULLY REVIEW THIS DOCUMENT.
        WE UNDERTAKE THE RESPONSIBLE STORAGE, PROCESSING, AND COLLECTION OF YOUR INFORMATION ONLY WHEN DEEMED NECESSARY AND RELEVANT TO OUR INTERACTIONS WITH YOU. THE INFORMATION SHARED WILL BE RETAINED FOR A DURATION MANDATED BY LAW OR AS LONG AS IT REMAINS PERTINENT TO THE PURPOSE FOR WHICH IT WAS INITIALLY COLLECTED. REST ASSURED, WE PLEDGE NOT TO DISCLOSE YOUR INFORMATION TO ANY THIRD PARTY WITHOUT YOUR EXPLICIT CONSENT, EXCEPT IN SITUATIONS WHERE LEGAL OBLIGATIONS COMPEL US TO DO SO.
        KINDLY PERUSE THE FOLLOWING FOR A COMPREHENSIVE UNDERSTANDING OF OUR METHODS IN COLLECTING AND DISSEMINATING INFORMATION:
        </p>
        <h1 style={{padding:'20px'}}>1. INFORMATION COLLECTION AT YOURINDIANSHOP</h1>
        <p style={{padding:'20px'}}>AT YOURINDIANSHOP, WE ARE COMMITTED TO MAINTAINING TRANSPARENCY AND ENSURING THE SECURITY OF YOUR INFORMATION. OUR OFFICERS, EMPLOYEES, AND APPOINTED AGENTS, AS NECESSARY, ARE DEDICATED TO THE RESPONSIBLE COLLECTION OF INFORMATION, WHICH MAY INCLUDE SENSITIVE PERSONAL DATA, WITH THE PRIMARY AIM OF ENHANCING OUR RELATIONSHIP WITH YOU.
            IT IS IMPORTANT FOR YOU TO ACKNOWLEDGE THAT WHILE USING OUR PLATFORM, YOU MAY SHARE INFORMATION THAT QUALIFIES AS "SENSITIVE PERSONAL INFORMATION" UNDER THE INFORMATION TECHNOLOGY ACT, 2000, AND THE INFORMATION TECHNOLOGY ACT (REASONABLE SECURITY PRACTICES AND PROCEDURES AND SENSITIVE PERSONAL DATA OR INFORMATION) RULES, 2011. YOUR CONSENT FOR THE UTILIZATION OF SUCH SENSITIVE PERSONAL INFORMATION IS HEREBY SOUGHT IN ACCORDANCE WITH THE PROVISIONS OUTLINED IN OUR PRIVACY POLICY.
            IN THE EVENT THAT YOU ARE UNABLE TO FURNISH THE REQUIRED INFORMATION, WE MAY REGRETTABLY BE UNABLE TO FULFILL YOUR REQUESTED PRODUCT OR SERVICE. THE TYPES OF INFORMATION WE GATHER ENCOMPASS BOTH USER-PROVIDED DATA AND INFORMATION RECEIVED FROM THIRD PARTIES.
        </p>
        <p style={{padding:'20px'}}>A.	USER-PROVIDED INFORMATION:
UPON REGISTERING FOR A USER ACCOUNT, YOU WILL FURNISH US WITH PERSONAL DETAILS SUCH AS YOUR FIRST NAME, LAST NAME, EMAIL, PHONE NUMBER, AND ANY OTHER PERTINENT INFORMATION. CORRESPONDENCES VIA EMAIL WILL BE RETAINED, INCLUDING THE CONTENT OF YOUR MESSAGES, EMAIL ADDRESS, AND OUR RESPONSES. ADDITIONALLY, ANY MESSAGES SENT THROUGH OUR SERVICES WILL BE PRESERVED. YOUR PERSONAL INFORMATION, BOTH PAST AND PRESENT, IS HELD IN OUR RECORDS TO MEET LEGITIMATE INTERESTS, COMPLY WITH LEGAL OBLIGATIONS, AND FULFILL CONTRACTUAL UNDERTAKINGS.
<br />B.	INFORMATION RECEIVED FROM THIRD PARTIES:
BEYOND THE INFORMATION DIRECTLY PROVIDED BY YOU, WE MAY ALSO RECEIVE DATA FROM THIRD PARTIES, ESPECIALLY IF YOU CHOOSE TO SIGN UP USING EXTERNAL ACCOUNTS LIKE GOOGLE OR FACEBOOK. INFORMATION FROM OTHER USERS, SOCIAL MEDIA INTERACTIONS, AND PARTNERSHIPS WITH BUSINESS PROMOTERS MAY CONTRIBUTE TO A COMPREHENSIVE UNDERSTANDING OF YOUR PROFILE.
<br />C.	NON-PERSONAL IDENTIFICATION INFORMATION:
WE GATHER NON-PERSONAL IDENTIFICATION INFORMATION WHENEVER USERS INTERACT WITH OUR PLATFORM. THIS INCLUDES BROWSER DETAILS, COMPUTER TYPE, TECHNICAL INFORMATION, AND CONNECTIVITY SPECIFICS, SUCH AS OPERATING SYSTEMS AND INTERNET SERVICE PROVIDERS.
<br />D.	LOG FILE AND LOCATION INFORMATION:
OUR SERVERS AUTOMATICALLY RECORD LOG FILE DETAILS, ENCOMPASSING WEB REQUESTS, IP ADDRESSES, BROWSER TYPES, URLS, AND USER INTERACTIONS. YOU HAVE THE OPTION TO SHARE YOUR LOCATION ALONG WITH PERSONAL INFORMATION, AND WE MAY UTILIZE DEVICE DATA, SUCH AS WIRELESS NETWORK INFORMATION OR IP ADDRESSES, FOR LOCATION DETERMINATION. THIS INFORMATION IS CRUCIAL FOR DELIVERING CUSTOMIZED FEATURES AND ENHANCING THE OVERALL QUALITY OF OUR SERVICES.
YOUR TRUST IS PARAMOUNT TO US, AND WE ARE COMMITTED TO SAFEGUARDING YOUR INFORMATION IN ADHERENCE TO THE HIGHEST STANDARDS.

        <h1 style={{padding:'20px'}}>2.	 UTILIZATION OF COLLECTED INFORMATION AT YOURINDIANSHOP</h1>
        <p style={{padding:'20px'}}>
AT YOURINDIANSHOP, WE CONSIDER THE PROTECTION AND EFFICIENT USE OF YOUR PERSONAL INFORMATION AS PARAMOUNT. WE UTILIZE THE PERSONAL INFORMATION YOU SHARE WITH US TO OPERATE, MAINTAIN, AND DELIVER THE FEATURES AND FUNCTIONALITY OF OUR PLATFORM. THE COLLECTION AND UTILIZATION OF USER DATA ARE DRIVEN BY A COMMITMENT TO ENHANCING YOUR OVERALL EXPERIENCE. HERE ARE THE KEY PURPOSES FOR WHICH WE MAY COLLECT AND USE YOUR PERSONAL INFORMATION:
        <br /><br />
        A. IMPROVING CUSTOMER SERVICE:
THE INFORMATION YOU PROVIDE PLAYS A CRUCIAL ROLE IN ENABLING US TO RESPOND PROMPTLY AND EFFICIENTLY TO YOUR CUSTOMER SERVICE REQUESTS AND SUPPORT NEEDS.
<br />B. PERSONALIZING USER EXPERIENCE:
WE AGGREGATE AND ANALYZE INFORMATION TO UNDERSTAND HOW OUR USERS INTERACT WITH THE SERVICES AND RESOURCES OFFERED ON THE PLATFORM. INTERNALLY, THIS DATA IS USED FOR PURPOSES SUCH AS ANALYZING SERVICE USAGE, DIAGNOSING TECHNICAL ISSUES, MAINTAINING SECURITY, AND PERSONALIZING CONTENT. WE LEVERAGE THIS INFORMATION TO RECOMMEND USER PROFILES AND ENSURE A COHESIVE EXPERIENCE FOR YOU.
<br />C.  MANAGING USER ACCOUNTS:
YOUR INFORMATION IS EMPLOYED TO OVERSEE THE REGISTRATION AND MANAGEMENT OF YOUR SERVICES, ENSURING A SEAMLESS AND SECURE USER EXPERIENCE.
<br />E.	COMMDUNICATIONS:
WE USE YOUR EMAIL ADDRESS TO ADDRESS YOUR INQUIRIES, QUESTIONS, AND REQUESTS. ADDITIONALLY, YOU MAY RECEIVE EMAILS CONTAINING YOURINDIANSHOP UPDATES, NEWS, RELATED PRODUCT OR SERVICE INFORMATION, AND MORE. YOU HAVE THE OPTION TO UNSUBSCRIBE FROM FUTURE EMAILS, AND DETAILED INSTRUCTIONS ARE PROVIDED IN EACH COMMUNICATION. YOUR CONSENT ALLOWS US TO USE YOUR EMAIL ADDRESS FOR SERVICE-RELATED NOTICES AND OTHER ESSENTIAL COMMUNICATION IN COMPLIANCE WITH LEGAL REQUIREMENTS.
<br />F.	AUDIT:
POST ACCOUNT TERMINATION OR DEACTIVATION, WE MAY RETAIN PROFILE INFORMATION AND USER CONTENT FOR A REASONABLE DURATION, PRIMARILY FOR BACKUP, ARCHIVAL, OR AUDIT PURPOSES. ANY INFORMATION CONTAINED IN YOUR COMMUNICATIONS POSTED TO PUBLIC OR SEMI-PUBLIC AREAS OF OUR SERVICES MAY BE RETAINED AND USED INDEFINITELY AFTER THE DEACTIVATION OF YOUR USER ACCOUNT.
<br />G.	OTHER PURPOSES:
WE MAY LEVERAGE YOUR INFORMATION FOR VARIOUS PURPOSES, INCLUDING BUT NOT LIMITED TO FRAUD PREVENTION, PROCESSING APPLICATIONS FOR SERVICES, HANDLING REQUESTS, MEETING CONTRACTUAL OBLIGATIONS, RESOLVING SERVICE-RELATED ISSUES, DEVELOPING PRODUCTS OR SERVICES TAILORED TO YOUR NEEDS, AND ENSURING LEGAL COMPLIANCE.
AT YOURINDIANSHOP, WE PRIORITIZE THE SECURITY, PRIVACY, AND SEAMLESS EXPERIENCE OF OUR USERS, AND YOUR TRUST IN OUR PLATFORM IS INTEGRAL TO OUR COMMITMENT.

        </p>
        </p>
        <h1 style={{padding:'20px'}}>4.	BROWSER USAGE AND COOKIES AT YOURINDIANSHOP</h1>
        <p style={{padding:"20px"}}>AT YOURINDIANSHOP, WE EMPLOY BROWSER USAGE AND UTILIZE COOKIES TO ENHANCE YOUR OVERALL EXPERIENCE ON OUR PLATFORM. COOKIES, SMALL IDENTIFIERS SENT FROM A WEB SERVER AND STORED ON YOUR COMPUTER'S HARD DRIVE, ARE REGULARLY PLACED TO OPTIMIZE VARIOUS ASPECTS OF YOUR INTERACTION WITH THE PLATFORM. THE PURPOSE OF THESE COOKIES IS MULTIFACETED:
<br />SESSION MANAGEMENT: COOKIES ASSIST IN KEEPING TRACK OF YOUR SESSION, ENSURING A SEAMLESS AND EFFICIENT USER EXPERIENCE.
<br />SHOPPING CART FUNCTIONALITY: WE UTILIZE COOKIES TO ENHANCE THE FUNCTIONALITY OF YOUR SHOPPING CART, STREAMLINING THE SHOPPING PROCESS FOR YOUR CONVENIENCE.
<br />PERSONALIZED ADVERTISING: COOKIES ENABLE US TO DELIVER ADVERTISING CONTENT TAILORED TO YOUR INTERESTS, ENHANCING THE RELEVANCE OF THE INFORMATION PRESENTED TO YOU.
<br />CONTENT CUSTOMIZATION: PERSONALIZED CONTENT DELIVERY IS FACILITATED THROUGH COOKIES, ENSURING THAT THE INFORMATION YOU RECEIVE ALIGNS WITH YOUR PREFERENCES.
<br />LOGIN INFORMATION: COOKIES ARE INSTRUMENTAL IN SAVING YOUR LOGIN INFORMATION, PROVIDING EASE OF ACCESS TO THE PLATFORM DURING SUBSEQUENT VISITS.
IT IS IMPORTANT TO NOTE THAT YOU HAVE THE OPTION TO ACCEPT OR DECLINE COOKIES. WHILE ACCEPTING COOKIES ENSURES THE OPTIMAL FUNCTIONING OF THE SITE AND ENABLES YOU TO ENJOY ALL FEATURES SEAMLESSLY, DECLINING COOKIES MAY IMPACT CERTAIN FUNCTIONALITIES, LEADING TO POTENTIAL LIMITATIONS IN SITE PERFORMANCE.
AT YOURINDIANSHOP, WE PRIORITIZE YOUR PRIVACY AND AIM TO PROVIDE YOU WITH A TAILORED AND EFFICIENT BROWSING EXPERIENCE. YOUR CHOICE REGARDING COOKIE ACCEPTANCE EMPOWERS YOU TO ALIGN YOUR BROWSING PREFERENCES WITH YOUR INDIVIDUAL NEEDS.
<br /><br />5.	 THIRD-PARTY ENGAGEMENT AT YOURINDIANSHOP
AT YOURINDIANSHOP, WE PRIORITIZE TRANSPARENCY AND SECURITY IN OUR ENGAGEMENT WITH THIRD-PARTY ENTITIES. IN CERTAIN INSTANCES, OUR PLATFORM MAY PRESENT URLS DIRECTING YOU TO OTHER PLATFORMS IN GOOD FAITH, AIMING TO COLLECT OR VERIFY YOUR PERSONAL INFORMATION. WE ARE COMMITTED TO MAKING REASONABLE EFFORTS TO ENSURE THAT THIRD-PARTY URLS MEET SIMILAR STANDARDS IN SAFEGUARDING INDIVIDUAL PRIVACY RIGHTS. IT IS IMPORTANT TO NOTE THAT WHILE WE STRIVE FOR PRIVACY STANDARDS, PLATFORMS NOT ASSOCIATED OR AUTHORIZED BY YOURINDIANSHOP MAY FEATURE WEB LINKS LEADING TO OUR PLATFORM, AND WE DISCLAIM ANY RESPONSIBILITY FOR THE CONTENT CONTAINED THEREIN. WE STRONGLY RECOMMEND REVIEWING THE INDIVIDUAL PRIVACY POLICIES OF THESE EXTERNAL SITES FOR A COMPREHENSIVE UNDERSTANDING.
ADVERTISEMENTS DISPLAYED ON OUR PLATFORM AND ANY ASSOCIATED PLATFORMS MAY BE PROVIDED BY THIRD PARTIES. THESE THIRD PARTIES, IN THE COURSE OF DISPLAYING ADVERTISEMENTS, MAY STORE YOUR IP ADDRESS AND LEVERAGE TECHNOLOGIES LIKE COOKIES AND JAVASCRIPT TO MONITOR, MEASURE, AND OPTIMIZE THEIR ADVERTISEMENTS. WHILE WE SHOWCASE THESE ADVERTISEMENTS, WE HAVE NO CONTROL OR ACCESS TO THE TECHNOLOGIES EMPLOYED BY THIRD-PARTY PLATFORMS. CLICKING ON THESE ADVERTISEMENTS AND PROVIDING INFORMATION TO THESE THIRD PARTIES IS ENTIRELY AT YOUR DISCRETION AND RISK. IT'S ESSENTIAL TO RECOGNIZE THAT THIS PRIVACY POLICY DOES NOT EXTEND TO TECHNOLOGIES INSTALLED BY THIRD-PARTY PLATFORMS ON YOUR DEVICES.
COLLABORATING WITH THIRD-PARTY PLATFORMS TO DISPLAY BANNERS OR ADVERTISEMENTS, WE ACKNOWLEDGE THAT THESE ENTITIES MAY SHARE DATA REGARDING THE EFFECTIVENESS OF OUR BANNERS OR ADVERTISEMENTS AND THE TRAFFIC GENERATED TOWARDS OUR PLATFORM. INFORMATION SHARED BY THIRD-PARTY PLATFORMS IS SUBJECT TO THEIR RESPECTIVE PRIVACY POLICIES, AND WE ENCOURAGE OUR USERS TO FAMILIARIZE THEMSELVES WITH THOSE POLICIES.
WHEN YOU GRANT PERMISSION FOR THIRD-PARTY PLATFORMS TO VIEW INFORMATION ON OUR PLATFORM, SUCH THIRD PARTIES MAY COLLECT AND PUBLISH INFORMATION ABOUT YOUR ACTIVITIES. SIMILARLY, SHARING YOUR VISITS OR ACTIVITIES ON OUR PLATFORM ALLOWS THIRD-PARTY PLATFORMS TO COLLECT AND PUBLISH INFORMATION ABOUT YOUR ENGAGEMENTS. REST ASSURED, ANY INFORMATION COLLECTED IS SUBJECT TO OUR PRIVACY POLICY, AND WE AFFIRM THAT NO CONTENT WILL BE PUBLISHED TO THIRD-PARTY PLATFORMS WITHOUT YOUR EXPLICIT APPROVAL.
UPON DISCONTINUING ACCESS TO A THIRD-PARTY PLATFORM, WE WILL CEASE COLLECTING YOUR DATA FROM THAT SOURCE, ALTHOUGH DATA COLLECTED PRIOR TO DISCONTINUATION WILL BE RETAINED. PERIODICALLY, WE MAY SEEK INFORMATION FROM THIRD PARTIES TO ENHANCE AND CUSTOMIZE OUR PLATFORM FEATURES IN ALIGNMENT WITH YOUR PREFERENCES.
MOREOVER, WE UTILIZE SPECIFIC TOOLS FOR DATA ANALYSIS, CUSTOMER BEHAVIOR STUDIES, SURVEYS, MARKETING, ETC. PLEASE REFER TO ANNEX 1 FOR COMPREHENSIVE DETAILS. ADDITIONALLY, WE HAVE IMPLEMENTED GOOGLE RECAPTCHA ON OUR PLATFORM TO PROTECT AGAINST SPAM AND ABUSE, AND YOUR USAGE OF RECAPTCHA IS SUBJECT TO THE GOOGLE PRIVACY POLICY AND GOOGLE’S TERMS OF USE.
<br /><br />6.	 SECURITY MEASURES AT YOURINDIANSHOP
AT YOURINDIANSHOP, WE PRIORITIZE THE SAFEGUARDING OF YOUR PRIVACY THROUGH ROBUST SECURITY STANDARDS AND STRICT COMPLIANCE WITH RELEVANT DATA PROTECTION LAWS. EMPLOYING A COMBINATION OF INDUSTRY-APPROVED PHYSICAL, ELECTRONIC, AND PROCEDURAL SAFEGUARDS, WE ENSURE THE COMPREHENSIVE PROTECTION OF YOUR INFORMATION THROUGHOUT ITS LIFECYCLE WITHIN OUR INFRASTRUCTURE OR THAT WHICH WE PROCURE FROM THIRD-PARTY PROVIDERS.
OUR COMMITMENT EXTENDS TO TAKING ALL REASONABLE MEASURES TO PREVENT THE MISUSE, LOSS, UNAUTHORIZED ACCESS, MODIFICATION, OR DISCLOSURE OF YOUR PERSONAL INFORMATION. FOR HEIGHTENED SECURITY, SENSITIVE DATA IS HASHED OR ENCRYPTED DURING STORAGE WITHIN OUR INFRASTRUCTURE. IT IS DECRYPTED, PROCESSED, AND PROMPTLY RE-ENCRYPTED OR DISCARDED WHEN NO LONGER NECESSARY. NOTWITHSTANDING, CERTAIN DATA MAY BE RETAINED EVEN AFTER ACCOUNT DELETION TO FULFILL LEGAL OBLIGATIONS AND MAINTAIN RECORDS FOR POTENTIAL DISPUTE RESOLUTION.
WHEN YOU INTERACT WITH YOUR ACCOUNT INFORMATION, WE PROVIDE A SECURE SERVER ENVIRONMENT TO ENHANCE THE CONFIDENTIALITY OF YOUR DATA. ALTHOUGH WE IMPLEMENT STRINGENT SECURITY MEASURES, IT'S IMPORTANT TO NOTE THAT NO METHOD OF INFORMATION TRANSMISSION OVER THE INTERNET CAN GUARANTEE ABSOLUTE SECURITY. CONSEQUENTLY, WE DO NOT WARRANT THE SECURITY OF INFORMATION TRANSMITTED TO US VIA EMAIL, ON OUR SOCIAL MEDIA PROFILES, OR OTHER PUBLIC FORUMS.
FURTHERMORE, YOURINDIANSHOP DISCLAIMS RESPONSIBILITY FOR ANY BREACH OF SECURITY OR ACTIONS IMPACTING YOUR PERSONAL INFORMATION DUE TO EXTERNAL FACTORS BEYOND OUR CONTROL. THIS INCLUDES BUT IS NOT LIMITED TO EVENTS SUCH AS FIRE, FLOOD, ACTS OF GOD, SABOTAGE, STRIKES, CIVIL COMMOTION, WAR, ACTS OF GOVERNMENT, COMPUTER HACKING, CRASHES, DAMAGE TO COMPUTER SOFTWARE OR HARDWARE, UNAUTHORIZED ACCESS, OR OTHER BREACHES OF SECURITY.
WE ARE DEDICATED TO MAINTAINING THE HIGHEST STANDARDS OF SECURITY AND CONTINUALLY STRIVE TO ENHANCE OUR PROTECTIVE MEASURES TO ENSURE THE CONFIDENTIALITY AND INTEGRITY OF YOUR INFORMATION. YOUR TRUST IS INTEGRAL TO OUR COMMITMENT TO PROVIDING A SECURE AND RELIABLE PLATFORM.




<br /><br />7.	 OPT-OUT OPTIONS AT YOURINDIANSHOP
AT YOURINDIANSHOP, WE VALUE YOUR PREFERENCES AND OFFER CLEAR OPTIONS FOR OPTING OUT OF COMMUNICATIONS. USERS HAVE THE FLEXIBILITY TO DECLINE RECEIVING COMMUNICATIONS FROM US ON BEHALF OF OUR PARTNERS. TO EXERCISE THIS CHOICE, YOU CAN OPT-OUT BY CLICKING ON THE UNSUBSCRIBE LINK PROVIDED IN OUR NEWSLETTERS OR BY ADJUSTING NOTIFICATION PREFERENCES WITHIN YOUR USER ACCOUNT. WE ARE COMMITTED TO RESPECTING YOUR CHOICES REGARDING COMMUNICATION PREFERENCES.
IT'S IMPORTANT TO NOTE THAT, DESPITE OPTING OUT OF CERTAIN COMMUNICATIONS, WE MAY STILL COLLECT NECESSARY INFORMATION WHEN YOU ENGAGE IN TRANSACTIONS ON THE PLATFORM. THIS COLLECTION ENSURES THAT WE FULFILL OUR COMMITMENT TO PROVIDING YOU WITH A SEAMLESS AND PERSONALIZED EXPERIENCE, TAILORED TO YOUR INDIVIDUAL NEEDS. YOUR PRIVACY AND COMMUNICATION PREFERENCES ARE FUNDAMENTAL TO OUR COMMITMENT, AND WE APPRECIATE YOUR TRUST IN YOURINDIANSHOP.
<br /><br />8.	MINORS' INFORMATION AT YOURINDIANSHOP
YOURINDIANSHOP IS DESIGNED AND DIRECTED TOWARDS INDIVIDUALS ABOVE THE AGE OF EIGHTEEN (18). WE ARE DEDICATED TO ENSURING THE PRIVACY AND SAFETY OF ALL USERS. IN THE EVENT THAT WE UNINTENTIONALLY COLLECT PERSONAL INFORMATION ABOUT INDIVIDUALS UNDER THE AGE OF EIGHTEEN (18), WE ARE COMMITTED TO PROMPTLY DELETING SUCH INFORMATION TO MAINTAIN COMPLIANCE WITH LEGAL STANDARDS AND TO UPHOLD OUR COMMITMENT TO SAFEGUARDING THE PRIVACY OF MINORS. YOUR TRUST AND CONFIDENCE IN YOURINDIANSHOP ARE OF UTMOST IMPORTANCE TO US.
<br /><br />9.	 UPDATES TO PRIVACY POLICY AT YOURINDIANSHOP
AT YOURINDIANSHOP, WE RECOGNIZE THE IMPORTANCE OF TRANSPARENCY AND ARE COMMITTED TO KEEPING YOU INFORMED ABOUT OUR PRIVACY PRACTICES. WE RETAIN THE RIGHT TO UPDATE OR MODIFY OUR PRIVACY POLICY AT ANY TIME. ANY SUCH CHANGES WILL BE COMMUNICATED ON PAGES WE CONSIDER APPROPRIATE. WE ENCOURAGE YOU TO REGULARLY REVIEW OUR PRIVACY POLICY TO STAY INFORMED ABOUT ANY MODIFICATIONS OR UPDATES. YOUR CONTINUED USE OF OUR SERVICES FOLLOWING CHANGES TO OUR PRIVACY POLICY INDICATES YOUR ACCEPTANCE OF THOSE REVISIONS. WE VALUE YOUR TRUST AND ARE DEDICATED TO PROVIDING YOU WITH CLEAR AND UPDATED INFORMATION ABOUT OUR PRIVACY PRACTICES AT YOURINDIANSHOP.
<br /><br />10.	 CONSENT AT YOURINDIANSHOP
YOURINDIANSHOP VALUES YOUR PRIVACY AND IS COMMITTED TO MAINTAINING THE HIGHEST STANDARDS OF DATA PROTECTION. BY SUBMITTING DATA TO US OR OUR DESIGNATED AGENTS, YOU PROVIDE YOUR EXPLICIT CONSENT TO THE USE OF YOUR DATA IN ACCORDANCE WITH THE GUIDELINES OUTLINED IN THIS PRIVACY POLICY. ADDITIONALLY, YOU AGREE TO THE TRANSFER AND PROCESSING OF YOUR PERSONAL DATA ACROSS NATIONAL BORDERS, ACKNOWLEDGING THAT YOUR DATA MAY BE PROCESSED AND STORED BY THIRD PARTIES LOCATED IN RESPECTIVE COUNTRIES.
WE ASSURE YOU THAT, IN ADHERENCE TO OUR COMMITMENT TO PRIVACY, WE DO NOT ENGAGE IN THE SALE OF YOUR PERSONAL INFORMATION IN ANY MANNER, EXCEPT AS EXPLICITLY STATED IN THIS PRIVACY POLICY. YOUR TRUST IS OF PARAMOUNT IMPORTANCE TO US, AND WE ARE DEDICATED TO FOSTERING 
TRANSPARENCY AND CLARITY REGARDING THE USAGE AND PROTECTION OF YOUR DATA.
IF YOU HAVE ANY INQUIRIES OR REQUIRE FURTHER CLARIFICATION ABOUT OUR PRIVACY POLICY, PLEASE FEEL FREE TO REACH OUT TO US AT GRIEVANCE@YOURINDIANSHOP.COM. WE ARE HERE TO ADDRESS YOUR CONCERNS AND ENSURE A SECURE AND TRUSTWORTHY EXPERIENCE AT YOURINDIANSHOP.






<br /><br /><br />11.	 QUERIES AND SUPPORT AT YOURINDIANSHOP <br />
IF YOU HAVE INQUIRIES REGARDING OUR PRIVACY POLICY OR WISH TO DISCUSS YOURINDIANSHOP'S INFORMATION COLLECTION, USAGE, AND DISCLOSURE PRACTICES, OUR DEDICATED SUPPORT TEAM IS HERE TO ASSIST YOU.
<br />NAME: YOURINDIANSHOP SUPPORT TEAM
<br />ADDRESS: 860/N Kailash Nagar More, G.T. Road Bandel, Opp- Little Flower Kids School, 
  Beside (Bhowal Marble Godown), Hooghly-712123. (WEST BENGAL) INDIA.
<br />PHONE: [+91 9331089123]
<br />EMAIL: SUPPORT@YOURINDIANSHOP.COM
<br />FEEL FREE TO REACH OUT TO OUR GRIEVANCE OFFICER WITH ANY CONCERNS OR QUESTIONS YOU MAY HAVE. WE ARE COMMITTED TO PROVIDING TRANSPARENT AND RESPONSIVE ASSISTANCE TO ENSURE YOUR EXPERIENCE WITH YOURINDIANSHOP IS SECURE AND SATISFACTORY.
</p>
        <div style={{marginBottom:"500px"}}></div>
    </div>
  )
}

export default PrivacyPolicy