import React from 'react'

function ProhabitedItems() {
  return (
    <div>
        <h1 style={{padding:"20px"}}>PROHIBITED ITEMS BY YOURINDIANSHOP </h1>
        <p style={{padding:"20px",paddingBottom:'500px'}}>
        YOURINDIANSHOP, CANNOT FACILITATE THE SHIPMENT OF CERTAIN PROHIBITED AND NON-APPROVED RESTRICTED ITEMS ON BEHALF OF ITS CUSTOMERS. IT IS CRUCIAL TO BE AWARE OF THE FOLLOWING RESTRICTIONS AND GUIDELINES WHEN USING OUR SHIPPING SERVICES:
GENERAL PROHIBITIONS:
<br /><br /><br/>1. ADULT MATERIAL<br/>
2. AGRICULTURE PRODUCTS (E.G., GINGER, GARLIC PASTE, OR WHOLE)<br/>
3. AIR CONDITIONER/PURIFIER<br/>
4. ALCOHOLIC BEVERAGES<br/>
5. ANIMAL PRODUCTS<br/>
6. ANIMAL SUPPLEMENT<br/>
7. ANTIQUES<br/>
8. BAKERY ITEMS<br/>
9. BATTERIES (PROPANE, BUTANE, HYDROGEN, HELIUM)<br/>
10. BATTERY SHELLS<br/>
11. BEVERAGES REQUIRING REFRIGERATION OR OTHER ENVIRONMENTAL CONTROL<br/>
12. BUBBLE GUM (SINGAPORE)<br/>
13. BULBS<br/>
14. CANDLES<br/>
15. CHARCOAL (POWDER, CREAM, ETC.)<br/>
16. CIGARETTE/E-CIGARETTE<br/>
17. COFFEE<br/>
18. COINS (SILVER/GOLD)<br/>
19. CURRENCY NOTES<br/>
20. DAL (LENTIL)<br/>
21. DAMAGED/BROKEN/USED PHONES OF ANY KIND<br/>
22. DEBIT/CREDIT CARD<br/>
23. DRIVING LICENCE<br/>
24. DRONE CAMERAS<br/>
25. DSLR CAMERA (WITHOUT LENS WE CAN SHIP)<br/>
26. DYES (HAIR, TEXTILE, ETC.)<br/>
27. GHEE<br/>
28. GOLD, SILVER, AND GOLD/SILVER PLATED PRODUCTS<br/>
29. GOVERNMENT-ISSUED DOCUMENTS<br/>
30. HAND SANITIZERS<br/>
31. HARD DISK CONTAINING DATA<br/>
32. HERBS<br/>
33. HIGH-VALUE GADGETS<br/>
34. HING (ASAFOETIDA)<br/>
35. HONEY<br/>
36. HOOKAH FLAVOURS<br/>
37. HOVERBOARD<br/>
38. HUMAN AND ANIMAL REMAINS, ASHES<br/>
39. INCENSE STICKS<br/>
40. INSULIN<br/>
41. LAPTOP/DESKTOPS<br/>
42. LASERS<br/>
43. LITHIUM BATTERIES<br/>
44. LIVE ORGANS OR HUMAN REMAINS<br/>
45. LOTTERY TICKETS, GAMBLING DEVICES<br/>
46. MAGNETS<br/>
47. MATCHBOX<br/>
48. MATTRESS<br/>
49. MEAT OF WILD ANIMALS<br/>
50. MEDICAL SAMPLES<br/>
51. MELTABLE CHOCOLATES<br/>
52. MILLETS<br/>
53. MONEY, FAKE/DUMMY/COLLECTABLE CASH, PAYMENT CARDS, TRAVELER CHEQUES<br/>
54. MOSQUITO REPELLENT<br/>
55. MUSTARD<br/>
56. N95 & 4 PLY, 8 PLY FACE MASKS<br/>
57. ORGANIC FOOD (ANY ITEMS WHICH HAVE NAMES AS ORGANIC CAN'T BE SHIPPED)<br/>
58. PAINTS<br/>
59. PASSPORTS, IDS, STAMPS, GIFT CARDS<br/>
60. PEACOCK FEATHERS (ANY BIRD)<br/>
61. PEPPER & SALT<br/>
62. PERFUMES<br/>
63. PERISHABLE FOODS<br/>
64. PICKLE<br/>
65. PLANTS & SEEDS (NEED PHYTOSANITARY CERTIFICATES FOR SEEDS)<br/>
66. PORNOGRAPHY<br/>
67. POWER BANK<br/>
68. RADAR DETECTORS<br/>
69. RICE<br/>
70. SAMBAC & TUBEROSE<br/>
71. SANDALWOOD & RED SANDAL<br/>
72. SEALANT<br/>
73. SPEAKERS<br/>
74. SPECTACLES & LENSES<br/>
75. STEEL COATING<br/>
76. TELEVISION<br/>
77. TONNER & INK<br/>
78. TOY WEAPONS, PAINT BALL GUNS AND BB GUNS, ANTIQUE WEAPONS, KNIVES AND SWORDS, FAKE GRENADES, ITEMS THAT COULD BE USED
<br /><br />IMPORTANT NOTES:
•	THE SHIPMENT OF SOME ITEMS MAY VARY DEPENDING ON THE DESTINATION COUNTRY, AS IT IS SPECIFIC TO THE CUSTOMS REGULATIONS OF THAT COUNTRY.
•	CUSTOMERS SHIPPING TO CHINA, BANGLADESH, SOUTH AFRICA, MEXICO, BRAZIL, JAPAN, TAIWAN, AFRICAN COUNTRIES MAY NEED TO HIRE A BROKER TO CLEAR CUSTOMS.
•	WE DO NOT SHIP TO PAKISTAN, MYANMAR, IRAN, IRAQ & TURKEY.
•	FOR ANY UNCERTAINTIES, PLEASE CONTACT OUR CUSTOMER SUPPORT TEAM BEFORE PLACING AN ORDER, AS CERTAIN SELLERS/E-COMMERCE PLATFORMS MAY NOT ACCEPT PRODUCT RETURNS.

        </p>
    </div>
  )
}

export default ProhabitedItems